name: Format PR
on: issue_comment
permissions:
  contents: write
  issues: write
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/format')
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Spotless
        id: spotlessCheck
        continue-on-error: true
        run: ./gradlew spotlessCheck
      - name: Apply and Commit Linted File
        if: ${{ steps.spotlessCheck.outcome == 'failure' }}
        run: |
          ./gradlew spotlessApply
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git commit -am "Automated Spotless Apply"
          git push
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.COMMENT_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            PR Formatted!